"""add expired_at to registrations

Revision ID: 229b04286d4a
Revises: 8f9537e81b63
Create Date: 2026-08-30 20:06:20.975182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '229b04286d4a'
down_revision: Union[str, Sequence[str], None] = '8f9537e81b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_staff',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'staff_id')
    )
    op.create_index(op.f('ix_events_is_archived'), 'events', ['is_archived'], unique=False)
    op.create_index(op.f('ix_events_is_published'), 'events', ['is_published'], unique=False)
    op.add_column('registrations', sa.Column('expired_at', sa.DateTime(), nullable=True))
    op.alter_column('registrations', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registrations', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('registrations', 'expired_at')
    op.drop_index(op.f('ix_events_is_published'), table_name='events')
    op.drop_index(op.f('ix_events_is_archived'), table_name='events')
    op.drop_table('session_staff')
    # ### end Alembic commands ###
