"""add capacity alerts

Revision ID: 97efff46b13b
Revises: c77d310065c1
Create Date: 2026-08-31 13:07:08.079717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97efff46b13b'
down_revision: Union[str, Sequence[str], None] = 'c77d310065c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capacity_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('last_filled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capacity_alerts_id'), 'capacity_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_capacity_alerts_session_id'), 'capacity_alerts', ['session_id'], unique=True)
    op.create_table('registration_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_history_actor_user_id'), 'registration_history', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_registration_history_id'), 'registration_history', ['id'], unique=False)
    op.create_index(op.f('ix_registration_history_registration_id'), 'registration_history', ['registration_id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.alter_column('users', 'role',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_registration_history_registration_id'), table_name='registration_history')
    op.drop_index(op.f('ix_registration_history_id'), table_name='registration_history')
    op.drop_index(op.f('ix_registration_history_actor_user_id'), table_name='registration_history')
    op.drop_table('registration_history')
    op.drop_index(op.f('ix_capacity_alerts_session_id'), table_name='capacity_alerts')
    op.drop_index(op.f('ix_capacity_alerts_id'), table_name='capacity_alerts')
    op.drop_table('capacity_alerts')
    # ### end Alembic commands ###
